pragma solidity >=0.5.0 <0.8.0;

struct SteakHouseV2.PoolInfo {
  address stakingToken;
  uint256 stakingTokenTotalAmount;
  uint32 lastRewardTime;
  uint256[] AccRewardsPerShare;
  uint256[] AllocPoints;
}

struct SteakHouseV2.UserInfo {
  uint256 amount;
  uint256[] RewardDebt;
  uint256[] RemainingRewards;
}

interface ISteakHouseV2 {
  event Deposit( address indexed user,uint256 indexed pid,uint256 amount ) ;
  event EmergencyWithdraw( address indexed user,uint256 indexed pid,uint256 amount ) ;
  event FeeCollected( address indexed user,uint256 indexed pid,uint256 amount ) ;
  event OwnershipTransferred( address indexed previousOwner,address indexed newOwner ) ;
  event Withdraw( address indexed user,uint256 indexed pid,uint256 amount ) ;
  function RewardTokens( uint256  ) external view returns (address ) ;
  function RewardsPerSecond( uint256  ) external view returns (uint256 ) ;
  function add( uint256[] memory _AllocPoints,address _stakingToken,bool _withUpdate ) external   ;
  function changeEndTime( uint32 addSeconds ) external   ;
  function collect( uint256 _amount ) external   ;
  function deposit( uint256 _pid,uint256 _amount ) external   ;
  function depositFee(  ) external view returns (uint256 ) ;
  function depositFeeReceiver(  ) external view returns (address ) ;
  function emergencyWithdraw( uint256 _pid ) external   ;
  function endTime(  ) external view returns (uint32 ) ;
  function getMultiplier( uint256 _from,uint256 _to ) external view returns (uint256 ) ;
  function getPoolInfo( uint256 _pid ) external view returns (SteakHouseV2.PoolInfo memory ) ;
  function getUserInfo( uint256 _pid,address _user ) external view returns (SteakHouseV2.UserInfo memory ) ;
  function harvestFee(  ) external view returns (uint256 ) ;
  function harvestFeeReceiver(  ) external view returns (address ) ;
  function massUpdatePools(  ) external   ;
  function owner(  ) external view returns (address ) ;
  function pendingRewards( uint256 _pid,address _user ) external view returns (uint256[] memory ) ;
  function poolLength(  ) external view returns (uint256 ) ;
  function renounceOwnership(  ) external   ;
  function set( uint256 _pid,uint256[] memory _AllocPoints,bool _withUpdate ) external   ;
  function setDepositFee( uint256 _depositFee ) external   ;
  function setDepositFeeReceiver( address _depositFeeReceiver ) external   ;
  function setHarvestFee( uint256 _harvestFee ) external   ;
  function setHarvestFeeReceiver( address _harvestFeeReceiver ) external   ;
  function setRewardTokens( address[] memory _RewardTokens ) external   ;
  function setRewardsPerSecond( uint256 _rewardsPerSecond,uint16 _rid,bool _withUpdate ) external   ;
  function startTime(  ) external view returns (uint32 ) ;
  function totalAllocPoints( uint256  ) external view returns (uint256 ) ;
  function transferOwnership( address newOwner ) external   ;
  function updatePool( uint256 _pid ) external   ;
  function withdraw( uint256 _pid,uint256 _amount ) external   ;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[{"internalType":"contract IERC20[]","name":"_RewardTokens","type":"address[]"},{"internalType":"uint256[]","name":"_RewardsPerSecond","type":"uint256[]"},{"internalType":"uint32","name":"_startTime","type":"uint32"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":true,"internalType":"uint256","name":"pid","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":true,"internalType":"uint256","name":"pid","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"EmergencyWithdraw","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":true,"internalType":"uint256","name":"pid","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"FeeCollected","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":true,"internalType":"uint256","name":"pid","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Withdraw","type":"event"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"RewardTokens","outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"RewardsPerSecond","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256[]","name":"_AllocPoints","type":"uint256[]"},{"internalType":"contract IERC20","name":"_stakingToken","type":"address"},{"internalType":"bool","name":"_withUpdate","type":"bool"}],"name":"add","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint32","name":"addSeconds","type":"uint32"}],"name":"changeEndTime","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"collect","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"},{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"deposit","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"depositFee","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"depositFeeReceiver","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"}],"name":"emergencyWithdraw","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"endTime","outputs":[{"internalType":"uint32","name":"","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_from","type":"uint256"},{"internalType":"uint256","name":"_to","type":"uint256"}],"name":"getMultiplier","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"}],"name":"getPoolInfo","outputs":[{"components":[{"internalType":"contract IERC20","name":"stakingToken","type":"address"},{"internalType":"uint256","name":"stakingTokenTotalAmount","type":"uint256"},{"internalType":"uint32","name":"lastRewardTime","type":"uint32"},{"internalType":"uint256[]","name":"AccRewardsPerShare","type":"uint256[]"},{"internalType":"uint256[]","name":"AllocPoints","type":"uint256[]"}],"internalType":"struct SteakHouseV2.PoolInfo","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"},{"internalType":"address","name":"_user","type":"address"}],"name":"getUserInfo","outputs":[{"components":[{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256[]","name":"RewardDebt","type":"uint256[]"},{"internalType":"uint256[]","name":"RemainingRewards","type":"uint256[]"}],"internalType":"struct SteakHouseV2.UserInfo","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"harvestFee","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"harvestFeeReceiver","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"massUpdatePools","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"},{"internalType":"address","name":"_user","type":"address"}],"name":"pendingRewards","outputs":[{"internalType":"uint256[]","name":"","type":"uint256[]"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"poolLength","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"},{"internalType":"uint256[]","name":"_AllocPoints","type":"uint256[]"},{"internalType":"bool","name":"_withUpdate","type":"bool"}],"name":"set","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_depositFee","type":"uint256"}],"name":"setDepositFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_depositFeeReceiver","type":"address"}],"name":"setDepositFeeReceiver","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_harvestFee","type":"uint256"}],"name":"setHarvestFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_harvestFeeReceiver","type":"address"}],"name":"setHarvestFeeReceiver","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"contract IERC20[]","name":"_RewardTokens","type":"address[]"}],"name":"setRewardTokens","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_rewardsPerSecond","type":"uint256"},{"internalType":"uint16","name":"_rid","type":"uint16"},{"internalType":"bool","name":"_withUpdate","type":"bool"}],"name":"setRewardsPerSecond","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"startTime","outputs":[{"internalType":"uint32","name":"","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"totalAllocPoints","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"}],"name":"updatePool","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_pid","type":"uint256"},{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/
