const { addressBook } = require("blockchain-addressbook");

let swaps = [
  {
    chain: "bsc",
    name: "PancakeSwap",
    strategy: "StrategyCommonChefLPWithGasThrottler",
    prefix: "CakeV2",
    beefyApiLp: "cakeLp",
    url: "exchange.pancakeswap.finance/#/",
    chef: addressBook.bsc.platforms.pancake.masterchef,
    router: addressBook.bsc.platforms.pancake.router,
    tokens: {
      reward: addressBook.bsc.tokens.CAKE,
      wnative: addressBook.bsc.tokens.WBNB,
    },
  },
  {
    chain: "bsc",
    name: "FarmHero",
    strategy: "",
    prefix: "FarmHero",
    beefyApiLp: "farmhero",
    url: "exchange.pancakeswap.finance/#/",
    chef: addressBook.bsc.platforms.farmhero.chef,
    router: addressBook.bsc.platforms.pancake.router,
    tokens: {
      reward: addressBook.bsc.tokens.HERO,
      wnative: addressBook.bsc.tokens.WBNB,
    },
  },
  {
    chain: "bsc",
    name: "ApeSwap",
    strategy: "StrategyCommonChefLPWithGasThrottler",
    prefix: "Banana",
    beefyApiLp: "apeLp",
    isDegens: true,
    url: "dex.apeswap.finance/#/",
    chef: addressBook.bsc.platforms.ape.masterape,
    router: addressBook.bsc.platforms.ape.router,
    tokens: {
      reward: addressBook.bsc.tokens.BANANA,
      wnative: addressBook.bsc.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "ApeSwap",
    strategy: "",
    prefix: "Ape",
    beefyApiLp: "apeLp",
    isDegens: true,
    url: "dex.apeswap.finance/#/",
    chef: addressBook.polygon.platforms.apeswap.minichef,
    router: addressBook.polygon.platforms.apeswap.router,
    tokens: {
      reward: addressBook.polygon.tokens.BANANA,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
  {
    chain: "bsc",
    name: "Bakery",
    strategy: "StrategyCommonChefLPWithGasThrottler",
    prefix: "Bakery",
    beefyApiLp: "bakeryLp",
    url: "bakeryswap.org/#/",
    chef: addressBook.bsc.platforms.bakery.masterchef,
    router: addressBook.bsc.platforms.bakery.router,
    tokens: {
      reward: addressBook.bsc.tokens.BAKE,
      wnative: addressBook.bsc.tokens.WNATIVE,
    },
  },
  {
    chain: "bsc",
    name: "Kebab",
    strategy: "StrategyCommonChefLPWithGasThrottler",
    prefix: "kebab",
    beefyApiLp: "kebabLp",
    url: "swap.kebabfinance.com/#/",
    chef: addressBook.bsc.platforms.kebab.masterchef,
    router: addressBook.bsc.platforms.kebab.router,
    tokens: {
      reward: addressBook.bsc.tokens.KEBAB,
      wnative: addressBook.bsc.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "JetSwap",
    strategy: "",
    prefix: "jetswap",
    beefyApiLp: "jetswapLp",
    url: "exchange.jetswap.finance/#/",
    chef: addressBook.polygon.platforms.jetswap.chef,
    router: addressBook.polygon.platforms.jetswap.router,
    tokens: {
      reward: addressBook.polygon.tokens.pWINGS,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
  {
    chain: "bsc",
    name: "JetSwap",
    strategy: "StrategyCommonChefLPWithGasThrottler",
    prefix: "Jetswap",
    beefyApiLp: "jetswapLp",
    url: "exchange.jetswap.finance/#/",
    chef: addressBook.bsc.platforms.jet.masterchef,
    router: addressBook.bsc.platforms.jet.router,
    tokens: {
      reward: addressBook.bsc.tokens.WINGS,
      wnative: addressBook.bsc.tokens.WNATIVE,
    },
  },
  {
    chain: "bsc",
    name: "Mdex",
    strategy: "StrategyMdexChefLPWithGasThrottler",
    prefix: "Mdex",
    beefyApiLp: "mdexBscLp",
    url: "exchange.pancakeswap.finance/#/",
    chef: addressBook.bsc.platforms.mdex.masterchef,
    router: addressBook.bsc.platforms.mdex.router,
    tokens: {
      reward: addressBook.bsc.tokens.MDX,
      wnative: addressBook.bsc.tokens.WNATIVE,
    },
    contracts: {
      strategy: "",
    },
  },
  {
    chain: "bsc",
    name: "Wault",
    strategy: "",
    prefix: "Wex",
    beefyApiLp: "waultLp",
    url: "swap.wault.finance/bsc/index.html#",
    chef: addressBook.bsc.platforms.wault.masterchef,
    router: addressBook.bsc.platforms.wault.router,
    tokens: {
      reward: addressBook.bsc.tokens.WEX,
      wnative: addressBook.bsc.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "Wault",
    strategy: "",
    prefix: "wex",
    beefyApiLp: "waultLp",
    url: "swap.wault.finance/polygon/index.html#",
    chef: addressBook.polygon.platforms.wault.masterchef,
    router: addressBook.polygon.platforms.wault.router,
    tokens: {
      reward: addressBook.polygon.tokens.WEXpoly,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "Sushi",
    strategy: "",
    prefix: "Sushi",
    beefyApiLp: "sushiLp",
    url: "app.sushi.com",
    chef: addressBook.polygon.platforms.sushi.minichef,
    router: addressBook.polygon.platforms.sushi.router,
    tokens: {
      reward: addressBook.polygon.tokens.SUSHI,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "Polygonfarm",
    strategy: "",
    prefix: "Polygonfarm",
    beefyApiLp: "polycatQuickLp",
    url: "quickswap.exchange",
    chef: addressBook.polygon.platforms.polycat.masterchef,
    router: addressBook.polygon.platforms.quickswap,
    tokens: {
      reward: addressBook.polygon.tokens.FISH,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "Polypup",
    strategy: "",
    prefix: "Polypup",
    beefyApiLp: "polypupLp",
    url: "quickswap.exchange",
    chef: addressBook.polygon.platforms.polypup,
    router: addressBook.polygon.platforms.quickswap,
    tokens: {
      reward: addressBook.polygon.tokens.PUP,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
  {
    chain: "polygon",
    name: "Mai",
    strategy: "",
    prefix: "Mai",
    beefyApiLp: "maiLp",
    url: "quickswap.exchange",
    chef: addressBook.polygon.platforms.mai.chef,
    router: addressBook.polygon.platforms.quickswap,
    tokens: {
      reward: addressBook.polygon.tokens.MAI,
      wnative: addressBook.polygon.tokens.WNATIVE,
    },
  },
];

module.exports = swaps;
