// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IBeefyVaultV8 {
    event AddStrategy(address indexed strategy, uint256 debtRatio);
    event Approval(
        address indexed owner,
        address indexed spender,
        uint256 value
    );
    event Deposit(
        address indexed caller,
        address indexed owner,
        uint256 assets,
        uint256 shares
    );
    event EmergencyShutdown(bool active);
    event InCaseTokensGetStuck(address token, uint256 amount);
    event Initialized(uint8 version);
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    event Reported(
        address indexed strategy,
        int256 roi,
        uint256 repayment,
        uint256 gains,
        uint256 losses,
        uint256 allocated,
        uint256 debtRatio
    );
    event SetBeefyFeeConfig(address beefyFeeConfig);
    event SetBeefyFeeRecipient(address beefyFeeRecipient);
    event SetKeeper(address keeper);
    event SetLockedProfitDegradation(uint256 degradation);
    event SetStrategyDebtRatio(address indexed strategy, uint256 debtRatio);
    event SetTvlCap(uint256 newTvlCap);
    event SetWithdrawMaxLoss(uint256 withdrawMaxLoss);
    event SetWithdrawalQueue(address[] withdrawalQueue);
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Withdraw(
        address indexed caller,
        address indexed receiver,
        address indexed owner,
        uint256 assets,
        uint256 shares
    );

    function DEGRADATION_COEFFICIENT() external view returns (uint256);

    function PERCENT_DIVISOR() external view returns (uint256);

    function __VaultManager_init(
        uint256 _tvlCap,
        address _keeper,
        address _beefyFeeRecipient,
        address _beefyFeeConfig
    ) external;

    function addStrategy(address strategy, uint256 debtRatio) external;

    function allowance(address owner, address spender)
        external
        view
        returns (uint256);

    function approve(address spender, uint256 amount) external returns (bool);

    function asset() external view returns (address);

    function availableCapital(address strategy) external view returns (int256);

    function balanceOf(address account) external view returns (uint256);

    function beefyFeeConfig() external view returns (address);

    function beefyFeeRecipient() external view returns (address);

    function convertToAssets(uint256 shares)
        external
        view
        returns (uint256 assets);

    function convertToShares(uint256 assets)
        external
        view
        returns (uint256 shares);

    function debtOutstanding(address strategy) external view returns (uint256);

    function decimals() external view returns (uint8);

    function decreaseAllowance(address spender, uint256 subtractedValue)
        external
        returns (bool);

    function deposit(uint256 assets, address receiver)
        external
        returns (uint256);

    function depositAll() external;

    function emergencyShutdown() external view returns (bool);

    function getPricePerFullShare() external view returns (uint256);

    function inCaseTokensGetStuck(address token) external;

    function increaseAllowance(address spender, uint256 addedValue)
        external
        returns (bool);

    function initialize(
        address _asset,
        string memory _name,
        string memory _symbol,
        uint256 _tvlCap,
        address _keeper,
        address _beefyFeeRecipient,
        address _beefyFeeConfig
    ) external;

    function keeper() external view returns (address);

    function lastReport() external view returns (uint256);

    function lockedProfit() external view returns (uint256);

    function lockedProfitDegradation() external view returns (uint256);

    function maxDeposit(address) external view returns (uint256);

    function maxMint(address) external view returns (uint256);

    function maxRedeem(address owner) external view returns (uint256);

    function maxWithdraw(address owner) external view returns (uint256);

    function mint(uint256 shares, address receiver) external returns (uint256);

    function name() external view returns (string memory);

    function owner() external view returns (address);

    function previewDeposit(uint256 assets) external view returns (uint256);

    function previewMint(uint256 shares) external view returns (uint256);

    function previewRedeem(uint256 shares) external view returns (uint256);

    function previewWithdraw(uint256 assets) external view returns (uint256);

    function redeem(
        uint256 shares,
        address receiver,
        address owner
    ) external returns (uint256);

    function redeemAll() external;

    function removeTvlCap() external;

    function renounceOwnership() external;

    function report(int256 roi, uint256 repayment) external returns (uint256);

    function revokeStrategy() external;

    function setBeefyFeeConfig(address newBeefyFeeConfig) external;

    function setBeefyFeeRecipient(address newBeefyFeeRecipient) external;

    function setEmergencyShutdown(bool active) external;

    function setKeeper(address newKeeper) external;

    function setLockedProfitDegradation(uint256 degradation) external;

    function setStrategyDebtRatio(address strategy, uint256 debtRatio) external;

    function setTvlCap(uint256 newTvlCap) external;

    function setWithdrawMaxLoss(uint256 newWithdrawMaxLoss) external;

    function setWithdrawalQueue(address[] memory _withdrawalQueue) external;

    function strategies(address)
        external
        view
        returns (
            uint256 activation,
            uint256 debtRatio,
            uint256 allocated,
            uint256 gains,
            uint256 losses,
            uint256 lastReport
        );

    function symbol() external view returns (string memory);

    function totalAllocated() external view returns (uint256);

    function totalAssets() external view returns (uint256);

    function totalDebtRatio() external view returns (uint256);

    function totalSupply() external view returns (uint256);

    function transfer(address to, uint256 amount) external returns (bool);

    function transferFrom(
        address from,
        address to,
        uint256 amount
    ) external returns (bool);

    function transferOwnership(address newOwner) external;

    function tvlCap() external view returns (uint256);

    function withdraw(
        uint256 assets,
        address receiver,
        address owner
    ) external returns (uint256);

    function withdrawAll() external;

    function withdrawMaxLoss() external view returns (uint256);

    function withdrawalQueue(uint256) external view returns (address);
}